# defines the base configuration options (file paths, etc, default style, etc)

config:
  style: sass
  style_output_path: stylesheets/sass/_sprites
  image_output_path: images/sprites/
  image_source_path: images/
  public_path: jekyll/
  sprites_class: 'sprite'
  class_separator: '-'
  default_format: png
  default_spacing: 50

# defines what sprite collections get created
images:
  - name:  small
    align: vertical
    sources:
      - icons/*.png
      - layout/email.png
      - layout/phone.png